Youshu:
  data_path: '../data/all'
  batch_size_train: 2048
  batch_size_test: 2048
  topk: [10, 20, 40, 80]

  embedding_size: 64
  num_layers: 1

  aff_ed_ratio: 0.5
  hist_ed_ratio: 0.5
  agg_ed_ratio: 0.5

  lr: 1.0e-3
  lambda2: 1.0e-4
  lambda1: 0.1

  max_temp: 10000

  epochs: 100
  test_interval: 5


NetEase:
  data_path: '../data/all'
  batch_size_train: 2048
  batch_size_test: 2048
  topk: [10, 20, 40, 80]

  embedding_size: 64
  num_layers: 1

  aff_ed_ratio: 0.1
  hist_ed_ratio: 0.3
  agg_ed_ratio: 0.1

  lr: 1.0e-3
  lambda2: 1.0e-4
  lambda1: 0.1

  max_temp: 10000

  epochs: 100
  test_interval: 5


iFashion:
  data_path: '../data/cold'
  batch_size_train: 2048
  batch_size_test: 2048
  topk: [10, 20, 40, 80]

  embedding_size: 64
  num_layers: 1

  aff_ed_ratio: 0.2
  hist_ed_ratio: 0.2
  agg_ed_ratio: 0

  lr: 1.0e-3
  lambda2: 4.0e-5
  lambda1: 0.5

  max_temp: 10000

  epochs: 100
  test_interval: 5

Steam:
  data_path: '../data/warm'
  batch_size_train: 2048
  batch_size_test: 2048
  topk: [1, 3, 5, 10]
  topk_valid: 3


  embedding_size: 64
  num_layers: 1

  aff_ed_ratio: 0.2
  hist_ed_ratio: 0.2
  agg_ed_ratio: 0.2

  residual_coff: 0.4

  lr: 3.0e-2
  lambda2: 1.0e-4
  lambda1: 0.1

  max_temp: 10000

  epochs: 100
  test_interval: 5

  aug_type: 'MD'